development:
  cloud_name: noll-fyra
  api_key: '635593972373272'
  api_secret: 3Ndy_TB7s2CUBosB9Ev02RQiFSM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: noll-fyra
  api_key: '635593972373272'
  api_secret: 3Ndy_TB7s2CUBosB9Ev02RQiFSM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: noll-fyra
  api_key: '635593972373272'
  api_secret: 3Ndy_TB7s2CUBosB9Ev02RQiFSM
  enhance_image_tag: true
  static_image_support: false
