# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d53e50cc76d665ce573ee7c47a707cd68f8908d4618504d4be380d0f4318f74628ec5cb5f6b2453864c57e547cb2f94e94528c1b2f0a060d1835b88811d08084
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  cloudinary_api_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:
  secret_key_base: ad6ccbb30880ff13ec2110e742197cdb9be4ec3922ed15b7668e91ed9dac7a5c972c5799bac625e3450e036872746e04ff1edec249c746f8aba1a98d0e242890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  cloudinary_api_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
